# Uncomment the next line to define a global platform for your project
# platform :ios, '9.3'

# Comment the next line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!

def shared_pods
    # Pods for BirdBlox
    # pod 'Swifter', :git => 'https://github.com/httpswift/swifter.git', :branch => 'stable'
    pod 'Zip', :git => 'https://github.com/marmelroy/Zip.git', :branch => 'master'
end

target 'BirdBlox' do
  shared_pods
end

target 'BirdBloxOSX' do
    shared_pods
end
