# Uncomment the next line to define a global platform for your project
platform :ios, '9.3'

target 'BirdBlox' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BirdBlox
  pod 'Swifter', :git => 'https://github.com/httpswift/swifter.git', :branch => 'stable'
end
